lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser

    resources "/", TopicController
  end

  scope "/auth", Discuss do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

end

lib/discuss/application.ex
defmodule Discuss.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Discuss.Repo,
      # Start the endpoint when the application starts
      DiscussWeb.Endpoint
      # Starts a worker by calling: Discuss.Worker.start_link(arg)
      # {Discuss.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/discuss/comment.ex
defmodule Discuss.Comment do
  import Ecto.Changeset
  use Ecto.Schema

  @derive {Jason.Encoder, only: [:content, :inserted_at, :user]}

  schema "comments" do
    field :content, :string
    belongs_to :user, Discuss.User
    belongs_to :topic, Discuss.Topic


    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content])
    |> validate_required([:content])
  end
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo,
    otp_app: :discuss,
    adapter: Ecto.Adapters.Postgres
end

lib/discuss/topic.ex
defmodule Discuss.Topic do
  import Ecto.Changeset
  use Ecto.Schema

  schema "topics" do
    field :title, :string

    belongs_to :user, Discuss.User
    has_many :comments, Discuss.Comment
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title])
    |> validate_required([:title])
  end

end

lib/discuss/user.ex
defmodule Discuss.User do
  import Ecto.Changeset
  use Ecto.Schema

  @derive {Jason.Encoder, only: [:email]}

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string

    has_many :topics, Discuss.Topic
    has_many :comments, Discuss.Comment

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end



end

lib/discuss_web/controllers/auth_controller.ex
defmodule Discuss.AuthController do
  use DiscussWeb, :controller
  plug Ueberauth
  alias Discuss.User
  alias Discuss.Repo


  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, params) do
    user_params =
      %{
        token: auth.credentials.token,
        email: auth.info.email,
        provider: "github"
      }

    changeset = User.changeset(%User{}, user_params)

    signin(conn, changeset)
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: Routes.topic_path(conn, :index))
  end

  defp signin(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "welcome!")
        |> put_session(:user_id, user.id)
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Error signing in")
        |> redirect(to: Routes.topic_path(conn, :index))
    end
  end

  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil ->
        Repo.insert(changeset)
      user ->
        {:ok, user}
    end
  end
end

lib/discuss_web/controllers/page_controller.ex
defmodule DiscussWeb.PageController do
  use DiscussWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  alias Discuss.Repo
  alias Discuss.Topic

  use DiscussWeb, :controller

  plug Discuss.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :check_topic_owner when action in [:update, :edit, :delete]

  def index(conn, _params) do
    IO.inspect(conn.assigns)
    topics = Repo.all(Topic)
    render conn, "index.html", topics: topics
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    render conn, "show.html", topic: topic
  end

  def new(conn, _params ) do
    struct = %Topic{}
    params = %{}
    changeset = Topic.changeset(struct, params)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"topic" => topic}) do
    changeset = Topic.changeset(%Topic{}, topic)

    changeset = conn.assigns.user
      |> Ecto.build_assoc(:topics)
      |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic Created")
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  def edit(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)

    render conn, "edit.html", changeset: changeset, topic: topic

  end

  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    old_topic = Repo.get( Topic, topic_id )
    changeset = Topic.changeset( old_topic, topic )

    case Repo.update(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic Update")
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset, topic: old_topic
    end
  end

  def delete(conn, %{"id" => topic_id} ) do
    topic = Repo.get!(Topic, topic_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Topic Deleted")
    |> redirect(to: Routes.topic_path(conn, :index))

    # case Repo.delete(topic_id) do
    #   {:ok, _topic} ->
    #     conn
    #     |> put_flash(:info, "Topic Deleted")
    #     |> redirect(to: Routes.topic_path(conn, :index))
    #   {:error, changeset} ->
    #     render conn, "edit.html", changeset: changeset, topic: old_topic
    # end
  end

  def check_topic_owner(conn, _params) do
    %{params: %{"id" => topic_id}} = conn

    if Repo.get(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You cannot edit that")
      |> redirect(to: Routes.topic_path(conn, :index))
      |> halt()
    end
  end
end

lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

lib/discuss_web/views/page_view.ex
defmodule DiscussWeb.PageView do
  use DiscussWeb, :view
end

lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Discuss · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = '<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", @conn.assigns.user.id) %>'
      <% end %>
    </script>

  </head>
  <body>
    <nav class="header">
      <div class="">
        <a href="" class="brand-logo">
          Discussions
        </a>

        <div class="right">
          <%= if @conn.assigns[:user] do %>
            <div>
              <%= link "Sign Out", to: Routes.auth_path(@conn, :signout) %>
            </div>
          <% else %>
            <div>
              <%= link "Sign in with Github", to: Routes.auth_path(@conn, :request, "github") %>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/discuss_web/templates/topic/edit.html.eex
<%= form_for @changeset, Routes.topic_path(@conn, :update, @topic), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>

    <%= submit "Save Topic", class: "btn btn-primary" %>
  </div>
<% end %>

lib/discuss_web/templates/topic/index.html.eex
<h2>Topics</h2>

<ul class="collection">
  <%= for topic <- @topics do %>
    <li class="collection-item">
      <%= link topic.title, to: Routes.topic_path(@conn, :show, topic) %>

      <%= if @conn.assigns.user do %>
        <%= if @conn.assigns.user.id == topic.user_id do %>
          <div class="right">
            <%= link "Edit", to: Routes.topic_path(@conn, :edit, topic) %>

            <%= link "Delete", to: Routes.topic_path(@conn, :delete, topic), method: :delete %>
          </div>
        <% end %>
      <% end %>

    </li>
  <% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: Routes.topic_path(@conn, :new), class: "btn-floating btn-large wave-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

lib/discuss_web/templates/topic/new.html.eex
<%= form_for @changeset, Routes.topic_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>

  </div>

  <%= submit "Save", class: "btn btn-primary" %>
<% end %>
<%# I can reference @changeset because it was passed to render function in controller %>

lib/discuss_web/templates/topic/show.html.eex
<h5 class="tpc__heading">
<%= @topic.title %>
</h5>

<div class="input-field">
  <ul class="collection"></ul>

  <textarea class="tpc__input"></textarea>

  <button class="btn tpc__button">Add Comment</button>


</div>

<script>
  document.addEventListener("DOMContentLoaded", function(){
    window.createSocket(<%= @topic.id %>)
  })
</script>


<style>
  .tpc__heading{
    text-align: center;
    margin:70px;
    font-size:40px;
    border-top: 1px solid #bbb;
    border-bottom: 1px solid #bbb;
    padding-top: 20px;
    padding-bottom: 20px;
  }

  .tpc__button{
    margin: auto;
    display: block;
  }
</style>